# Generated by Django 4.2.4 on 2023-08-28 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatheralertconfig",
            old_name="state",
            new_name="state_abbreviation",
        ),
    ]
