# Generated by Django 4.2.4 on 2023-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_rename_state_weatheralertconfig_state_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatheralertconfig",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Extreme", "Extreme"),
                    ("Severe", "Severe"),
                    ("Moderate", "Moderate"),
                    ("Minor", "Minor"),
                    ("Unknown", "Unknown"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
